# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-12-26 18:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FriendRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=1)),
                ('created_at_ts', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('last_seen_ts', models.DateTimeField(auto_now_add=True)),
                ('created_at_ts', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='friendrelation',
            name='friend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend', to='friends.Users'),
        ),
        migrations.AddField(
            model_name='friendrelation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='friends.Users'),
        ),
        migrations.AlterUniqueTogether(
            name='friendrelation',
            unique_together=set([('user', 'friend')]),
        ),
    ]
